# Choose the global island type that will be on whole server for all people.
# Available: sky, water
global-island-type: sky

database:
  # Database host address, default = localhost
  host: localhost
  # Database port, default = 3306
  port: 3306
  # Database name, default = minecraft
  database: minecraft
  # Database user, default = root
  user: root
  # Database password
  password: password
  # Connect to database over SSL, default = false
  enable-ssl: false
  # Overrides the size of the database connection pool, default = 10
  maximum-pool-size: 10
  # Connection timeout in milliseconds, default = maximum size of signed int
  connection-timeout: 5000